# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
tags - Tag.create([
  { name: 'undergraduate'},
  { name: 'graduate school'},
  { name: 'phd'},
  { name: 'major (undergraduate)'},
  { name: 'studying computer science'},
  { name: 'mentorship'},
  { name: 'applying to internships'},
  { name: 'internships'},
  { name: 'applying to undergrad'},
  { name: 'product management'},
  { name: 'racism'},
  { name: 'sexism'},
  { name: 'homophobia'},
  { name: 'transphobia'},
  { name: 'interviews'},
  { name: 'work-life balance'},
  { name: 'applying to jobs'},
  { name: 'career advice'},
  { name: 'imposter syndrome'},
  { name: 'java'},
  { name: 'css'},
  { name: 'python'},
  { name: 'user interface'},
  { name: 'textbooks'},
  { name: 'community college'},
  { name: 'scala'},
  { name: 'ruby'},
  { name: 'ruby on rails'},
  { name: 'exchange trips'},
  { name: 'career advancement'},
  { name: 'promotions'},
  { name: 'salary negotiation'},
  { name: 'housing'},
  { name: 'job interview'},
  { name: 'code2040'},
  { name: 'return offer'},
  { name: 'stanford university'},
  { name: 'brooklyn college'},
  { name: 'mills college'},
  { name: 'career goals'},
  { name: 'harvard'},
  { name: 'harvey mudd'},
  { name: 'communication with manager'},
  { name: 'cowerkers'},
  { name: 'public speaking'},
  { name: 'substance abuse'},
  { name: 'stress management'},
  { name: 'mental health'},
  { name: 'financial advice'},
  { name: 'startup'},
  { name: 'entrepreneurship'},
  { name: 'resume'},
  { name: 'peer'},
  { name: 'coach'},
  { name: 'sponsor'},
  { name: 'hiring'}
])